### ISSUE TITLE
Apply the constraint of the quantity of items that can be added to cart dynamically after each purchase.

### ISSUE THREAD

**Issue by howardxhc** [CSC207-UofT/course-project-hairless-codemen#28]
We have a constraint on how many items can be added to the shopping cart, but only after the order is successfully generated will the quantity of the items in the cart be reduced from the storage. So for example if I have three apples, user1 adds two apples to the shopping cart, and user2 adds two apples to the shopping cart. There is no problem so far. But once user1 pays, user2's shopping cart must be able to report an error successfully, because storage only has 1 apple at that time.

**Comment by liuqin26** [comment]
Understood. When this case happens, should we throw exceptions(for backend coding) and notify the user the item(s) they've added to their cart have insufficient stock(on UI level)?

**Comment by howardxhc** [comment]
> Understood. When this case happens, should we throw exceptions(for backend coding) and notify the user the item(s) they've added to their cart have insufficient stock(on UI level)?

Yes, we may need to. At the moment the order is generated for user1, the shopping carts of all the people who have added more than the remaining quantity of the item in our storage should be put on some kind of label, so when these group of users log in, they can know.
