### ISSUE TITLE
Phase2 UI enhancement 

### ISSUE THREAD

**Issue by InxiQ** [CSC207-UofT/course-project-hairless-codemen#29]
Hi guys can you list all the areas you want to improve or add in UI for phase 2 so I can work on it?

**Comment by Parkrytom** [comment]
the layout of sell frame in UI

**Comment by InxiQ** [comment]
> the layout of sell frame in UI

Fixing it now

**Comment by EVAXZC** [comment]
wow that's great.

**Comment by howardxhc** [comment]
> wow that's great.

^

**Comment by liuqin26** [comment]
Username and password constraints when trying to create a new account.
User should be notified that:

- Username and password must be non-empty (i.e. username that is made of all blank spaces is not allowed )
- Password should have a minimum length of 8, at least one uppercase letter, one lowercase letter, one digit and one special character

Thanks a lot!

**Comment by InxiQ** [comment]
@liuqin26 Thanks got it.
