### ISSUE TITLE
Accessing Item Quantity on Controller Level

### ISSUE THREAD

**Issue by liuqin26** [CSC207-UofT/course-project-hairless-codemen#36]
I noticed that there is no method on the controller level that allows us to access the quantity of an item. But all the classes in Controller now don't seem to be an appropriate class to add such methods. Does anyone have an idea of how we can implement this?
Thanks!

**Comment by howardxhc** [comment]
I think we should implement the method in InfoFacade, and follow clean architecture in this way: InfoFacade -> ItemManager -> ItemStorage

**Comment by Parkrytom** [comment]
I think we need to rewrite codes in addElement and removeElement in ItemStorage first.

**Comment by liuqin26** [comment]
> I think we need to rewrite codes in addElement and removeElement in ItemStorage first.

Do you mind specifying the details of where we need to modify? I recognize that we only want to add the quantity of an item if that item's name is already in the storage. What else do we need?

**Comment by Parkrytom** [comment]
We need to make sure that the other information(seller name, category, price) of this item is the same as that of the existing item before we modify the quantity of the item directly. Otherwise, we can only add a whole item into Itemstorage.

**Comment by liuqin26** [comment]
> > Do you mind specifying the details of where we need to modify? I recognize that we only want to add the quantity of an item if that item's name is already in the storage. What else do we need?
> 
> We need to make sure that the other information(seller name, category, price) of this item is the same as that of the existing item before we modify the quantity of the item directly. Otherwise, we can only add a whole item into Itemstorage.

Got it. If we are trying to delete an item, and the quantity goes down to 0, we should just remove this item entirely from the storage? I will be putting down the definition of "what is an identical item" in the docstring of those methods. And how are we going to compare between items?

**Comment by Parkrytom** [comment]
> > > Do you mind specifying the details of where we need to modify? I recognize that we only want to add the quantity of an item if that item's name is already in the storage. What else do we need?
> > 
> > 
> > We need to make sure that the other information(seller name, category, price) of this item is the same as that of the existing item before we modify the quantity of the item directly. Otherwise, we can only add a whole item into Itemstorage.
> 
> Got it. If we are trying to delete an item, and the quantity goes down to 0, we should just remove this item entirely from the storage? I will be putting down the definition of "what is an identical item" in the docstring of those methods. And how are we going to compare between items?

Yes! We need to delete the item if the quantity of the item becomes 0. Also, we can compare the "print" results of the two items to see if they are identical.

**Comment by howardxhc** [comment]
> > > > Do you mind specifying the details of where we need to modify? I recognize that we only want to add the quantity of an item if that item's name is already in the storage. What else do we need?
> > > 
> > > 
> > > We need to make sure that the other information(seller name, category, price) of this item is the same as that of the existing item before we modify the quantity of the item directly. Otherwise, we can only add a whole item into Itemstorage.
> > 
> > 
> > Got it. If we are trying to delete an item, and the quantity goes down to 0, we should just remove this item entirely from the storage? I will be putting down the definition of "what is an identical item" in the docstring of those methods. And how are we going to compare between items?
> 
> Yes! We need to delete the item if the quantity of the item becomes 0. Also, we can compare the "print" results of the two items to see if they are identical.

Yes, but currently our print methods will also print the quantity of the item, so we can write a new toString method that ignores the quantity of the item and compare using this method.

**Comment by liuqin26** [comment]
> > > > > Do you mind specifying the details of where we need to modify? I recognize that we only want to add the quantity of an item if that item's name is already in the storage. What else do we need?
> > > > 
> > > > 
> > > > We need to make sure that the other information(seller name, category, price) of this item is the same as that of the existing item before we modify the quantity of the item directly. Otherwise, we can only add a whole item into Itemstorage.
> > > 
> > > 
> > > Got it. If we are trying to delete an item, and the quantity goes down to 0, we should just remove this item entirely from the storage? I will be putting down the definition of "what is an identical item" in the docstring of those methods. And how are we going to compare between items?
> > 
> > 
> > Yes! We need to delete the item if the quantity of the item becomes 0. Also, we can compare the "print" results of the two items to see if they are identical.
> 
> Yes, but currently our print methods will also print the quantity of the item, so we can write a new toString method that ignores the quantity of the item and compare using this method.

Sounds great. Will implement this idea tonight.
