### ISSUE TITLE
Targeted Demographics of Our Program

### ISSUE THREAD

**Issue by howardxhc** [CSC207-UofT/course-project-hairless-codemen#39]
1. Who should we market our program towards, if you were to sell or license your program to customers?
2. Whether or not your program is less likely to be used by certain demographics.

**Comment by liuqin26** [comment]
Since our program doesn't support any language other than English, so I would say that our program targets the English-speaking population. 

I wonder if there is a way to simply change the system language? If that's not too much work for UI, maybe we can add this as a feature to accommodate accessibility.

**Comment by zhen-s** [comment]
For example a simple diagram that's easy to understand on each of the buttons?

**Comment by Feihao-Ricardo-Qu** [comment]
Our program is facing customers who use the internet regularly and are familiar with online shopping. 

People who only like to shop in person may never use this program.

**Comment by EVAXZC** [comment]
I think everyone who wants to sell idle items in their home could use this application. Our application provided a free market for the users to trade on this platform. They can decide the price on their own.

**Comment by zhuhongd** [comment]
The target group can be anyone who wants to sell and buy second-handed items. Since our platform's sellers are not certified sellers, it could be anyone, it is not suggestible if someone wants to buy a brand new item, and come to our platform because we cannot guarantee the authenticity of the item
