### ISSUE TITLE
I want to add a new feature for our program

### ISSUE THREAD

**Issue by EVAXZC** [CSC207-UofT/course-project-hairless-codemen#40]
I would like to add one more feature to our application like deleting the user from the database.
Do you have any suggestions for this idea?

**Comment by howardxhc** [comment]
Deleting the user from our system sounds good.
I am thinking, also being able to "like" or "dislike" an item is something that can be considered too.

**Comment by InxiQ** [comment]
I think instead of this feature, we can add features that allow sellers to see who has bought their stuff, which I think would make our platform more reasonable.

**Comment by zhuhongd** [comment]
Totally agree with Qin and Howard! 

Besides adding a 'like' and 'dislike' button, can we also add a 'comment' button?

**Comment by liuqin26** [comment]
> I would like to add one more feature to our application like deleting the user from the database. Do you have any suggestions for this idea?

That's a totally reasonable feature. I was just wondering if a user wishes to delete his/her account from our platform, where should we give him/her the option on UI? I am thinking on the homepage there appears to be a button, but does anyone have a better idea?
